name: Release Creation

on:
  release:
    types: [published]

permissions:
  contents: write  # Required to upload assets to the release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract tag name
      id: extract_tag
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        VERSION="${TAG_NAME#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Show extracted version
      run: |
        echo "Tag: $TAG_NAME"
        echo "Version (no 'v'): $VERSION"

    - name: Update module.json with versioned URLs
      run: |
        jq ".version = \"$VERSION\" |
            .manifest = \"https://github.com/${{ github.repository }}/releases/latest/download/module.json\" |
            .download = \"https://github.com/${{ github.repository }}/releases/download/$TAG_NAME/module.zip\"" module.json > tmp.json
        mv tmp.json module.json

    - name: List files before zipping
      run: ls -al

    - name: Create ZIP package
      run: |
        zip -r module.zip module.json README.md main.js scripts/ styles/ templates/ lang/ || zip -r module.zip module.json README.md main.js styles/ lang/

    - name: List files before upload
      run: ls -al

    - name: Upload assets to release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: false
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'module.json,module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: "Automatic release of Wanted Level module."
